from . import account_payment
from . import account_payment_register
from . import account_move
from . import res_company
from . import res_config_settings
from . import payment_approval_history
from . import payment_workflow_stage
from . import res_partner
from . import account_journal
from . import res_partner