from . import account_journal
from . import account_move
from . import account_payment
from . import account_payment_register
from . import ir_actions_report
from . import payment_approval_history
from . import payment_dashboard
from . import payment_qr_verification
from . import payment_reminder
from . import payment_workflow_stage
from . import res_company
from . import res_config_settings
from . import res_partner
